[package]
name = "stk2fasta"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
regex = "1.11.1"

[dev-dependencies]
assert_cmd = "2.0.16"
pretty_assertions = "1.4.1"
rand = "0.9.0"
tempfile = "3.16.0"
